version: '3.8'
name: code-me-pro-assisgment
services:

  mysql-server:
    container_name: mysql-server
    hostname: mysql
    image: guna3006/mysql-codemepro:1.0.0
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      codemepro-network:
        ipv4_address: 30.0.0.5
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]

  backend-server:
    container_name: backend-server
    hostname: backend
    image: guna3006/backend-codemepro:1.0.0
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      codemepro-network:
        ipv4_address: 30.0.0.6
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
    depends_on:
      - mysql-server

  frontend-server:
    container_name: frontend-server
    hostname: frontend
    image: guna3006/frontend-codemepro:1.0.0
    restart: unless-stopped
    ports:
      - 8080:3000
    networks:
      codemepro-network:
        ipv4_address: 30.0.0.7
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
    depends_on:
      - backend-server


networks:
  codemepro-network:
    driver: bridge
    ipam:
     config:
       - subnet: 30.0.0.0/16
         gateway: 30.0.0.1